AWSTemplateFormatVersion: 2010-09-09
Description: This template create a security group.
Parameters:
  myVPC:
    Description: VPC id of your environment
    Type: String
    Default: vpc-19ebd071
Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow port 22 and http traffic
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
Outputs:
  SecurityGroupID:
    Description: Security Group ID
    Value: !Ref SecurityGroup
